language: go

matrix:
  include:
  - go: "1.10.x"
    script: sudo apt-get -y install libsdl2-dev && go build 
  - go: "1.11.x"
    script: sudo apt-get -y install libsdl2-dev && go build 

env:
  - GO111MODULE=on

install: true