language: go

env:
  - GO111MODULE=on

matrix:
  include:
  - go: "1.11.x"
    script: sudo apt-get -y install libsdl2-dev && go get && go build
    cache:
      directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/pkg/mod

install: true