
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: echo "Teste" > test.cache.yml
      - restore_cache:
          keys: teste.cache
      - save_cache:
          key: teste.cache
