version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: echo "Teste" > test.cache.txt
      - run: echo "Teste" > test.artifact.txt
      - restore_cache:
          keys: teste.cache
      - save_cache:
          key: teste.cache
          paths:
            - test.cache.txt
      - store_artifacts:
          path: test.artifact.txt
          destination: test.artifact.txt
  build2:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: echo "Teste" > test.cache.txt
      - run: echo "Teste" > test.artifact.txt
      - restore_cache:
          keys: teste.cache
      - save_cache:
          key: teste.cache
          paths:
            - test.cache.txt
      - store_artifacts:
          path: test.artifact.txt
          destination: test.artifact.txt
workflows:
  version: 2
  build_nodejs:
    jobs:
      - build
      - build2